### ISSUE TITLE
Mettre un analytics sur le site

### ISSUE THREAD

**Issue by juliendorra** [amontourdeprogrammer/amontourdeprogrammer.github.io#10]

**Comment by yaf** [comment]
Possible de le faire via cloudfare, mais il me faut le compte google analytics :-)

**Comment by mathildeToucheboeuf** [comment]
Et voila l id de tracking UA-109408936-1


Le 8 nov. 2017 16:55, "Yannick François" <notifications@github.com> a
écrit :

**Comment by yaf** [comment]
done
